format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$golang\
$java\
$rust\
[](fg:#86BBD8 bg:#6f618b)\
$status\
[](fg:#6f618b)\
$fill\
[](fg:#6f618b fg:#6f618b)\
$cmd_duration\
[](fg:#6f618b fg:#6f618b)
[↪ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[fill]
symbol = " "
#style = "bg:#6f618b"
disabled = false

[cmd_duration]
min_time = 1
style = "bg:#6f618b fg:white"
format = '[$duration]($style)'
#show_notifications = true
#show_milliseconds = true
#min_time_to_notify = 1

[status]
style = "bold bg:#6f618b fg:white"
symbol = "✖"
success_symbol = ""
#format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
format = "[ $symbol $status]($style)"
map_symbol = true
disabled = false

[line_break]
disabled = true


# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = false
style_user = "bold bg:#9A348E fg:#FFF27D"
style_root = "bg:#9A348E fg:#AAF27D"
format = '[$user]($style)'

[directory]
style = "bg:#DA627D"
read_only = ""
format = "[ $path ]($style)"
truncation_symbol = "…/"
truncation_length = 80
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A fg:white"
format = '[ ♥ $time ]($style)'
